#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

APP="$1"
IMAGE="dokku/$APP"
CURRENT_PLUGIN_DIR=$(dirname $0)

echo "-----> Adding SSH keys to build environment ..."

id=$(cat $CURRENT_PLUGIN_DIR/add-ssh-keys | docker run -i -a stdin $IMAGE /bin/bash -c "cat | bash -");
test $(docker wait $id) -eq 0

docker commit $id $IMAGE > /dev/null

