#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

APP="$1";
IMAGE="dokku/$APP"
CACHE_DIR=$DOKKU_ROOT/$APP/cache

echo "-----> Cacheing vendors"

id=$(docker run -d -v $CACHE_DIR:/cache $IMAGE rsync -a --delete /app/vendor /cache/)
test $(docker wait $id) -eq 0

