#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

APP="$1"
IMAGE="dokku/$APP"
CACHE_DIR=$DOKKU_ROOT/$APP/cache
VENDOR_CACHE="$CACHE_DIR/vendor"

if [[ ! -d $VENDOR_CACHE ]] ;
then 
	exit;
fi;

echo "-----> Restoring cached vendors"

id=$(docker run -d -i -v $CACHE_DIR:/cache $IMAGE rsync -a --delete --exclude php/ --exclude nginx/ --exclude libicu/ --exclude libmcrypt/ /cache/vendor /app/)
test $(docker wait $id) -eq 0

docker commit $id $IMAGE > /dev/null

