#!/usr/bin/env bash
set -eo pipefail; [[ "$DOKKU_TRACE" ]] && set -x

APP="$1";
IMAGE="dokku/$APP"
PLUGIN_ROOT=$(dirname $0)

id=$(cat $PLUGIN_ROOT/release-symfony | docker run -i -a stdin $IMAGE /bin/bash -c "bash - ")
docker attach $id
test $(docker wait $id) -eq 0
docker commit $id $IMAGE > /dev/null
